name: PHP Composer

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: phrase/phrase-cli:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Git
      run: apk add git
    
    - name: Show Git info
      run: apk info git


