name: PHP Composer

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

permissions:
  contents: read

env:
  PIPELINE_BRANCH_NAME: pipeline

jobs:
  build:

    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - uses: actions/checkout@v3

    - name: Setup Git, cUrl, Brew, Phrase
      run: |
        lsb_release -a
        sudo apt-get install git
        git --version
        which git
        git config --global user.email "pipeline@github.com"
        git config --global user.name "pipeline"
        sudo apt-get install curl
        curl --version
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bash_profile
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew --version
        brew install phrase-cli
        echo 'Phrase version is:'
        phrase version

    - name: Make changes
      run: |
        echo $PIPELINE_BRANCH_NAME
        git branch -D $PIPELINE_BRANCH_NAME || true
        git checkout -b $PIPELINE_BRANCH_NAME
        echo "test333" >> test
        git add .
        git commit -m "commit from pipeline"
        git push --set-upstream origin $PIPELINE_BRANCH_NAME --force
        git checkout -b test
        git merge $PIPELINE_BRANCH_NAME
        git push

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.usr/bin/git
          ~/.usr/bin/curl
          ~/home/linuxbrew/.linuxbrew/bin/brew
          ~/home/linuxbrew/.linuxbrew/Cellar/phrase-cli
          ~/home/runner/.bash_profile
        restore-keys: |
          git
          curl
          brew
          phrase
          bash


