name: PHP Composer

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Git
      run: sudo apt install git
    
    - name: Show Git info
      run: git --version

    - name: Create branch
      run: git checkout -b $(date + ci%Y%m%d%H%M%S)


