name: PHP Composer

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

permissions:
  contents: read

env:
  PIPELINE_BRANCH_NAME: pipeline

jobs:
  build:

    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: Setup Git, cUrl, Brew, Phrase, pull translations
      env:
        PHRASE_ACCESS_TOKEN: ${{ secrets.PHRASE_ACCESS_TOKEN }}
        PHRASE_PROJECT_ID: ${{ secrets.PHRASE_PROJECT_ID }}
      run: |
        cat phrase.yml
        lsb_release -a
        sudo apt-get install git
        git --version
        which git
        git config --global user.email "pipeline@github.com"
        git config --global user.name "pipeline"
        sudo apt-get install curl
        curl --version
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bash_profile
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew --version
        brew install phrase-cli
        echo 'Phrase version is:'
        phrase version
        echo $PIPELINE_BRANCH_NAME
        git branch -D $PIPELINE_BRANCH_NAME || true
        git checkout -b $PIPELINE_BRANCH_NAME
        phrase pull
        ls
  
    - name: Cache dependencies
      uses: actions/cache@v3
      env:
        cache-name: cache-git-curl-brew-phrase-profile
      with:
        path: |
          ~/.usr/bin/git
          ~/.usr/bin/curl
          ~/home/linuxbrew/.linuxbrew/bin/brew
          ~/home/linuxbrew/.linuxbrew/Cellar/phrase-cli
          ~/home/runner/.bash_profile
        key: cache-git-curl-brew-phrase-profile
        restore-keys: cache-git-curl-brew-phrase-profile


