name: PHP Composer

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

permissions:
  contents: read

env:
  PIPELINE_BRANCH_NAME: pipeline

jobs:
  build:

    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - uses: actions/checkout@v3

    - name: Git setup
      run: |
        lsb_release -a
        sudo apt install git
        git --version
        which git
        git config --global user.email "pipeline@github.com"
        git config --global user.name "pipeline"

    - name: Phrase setup
      run: |
        sudo apt install curl
        curl --version

    - name: Make changes
      run: |
        echo $env.PIPELINE_BRANCH_NAME
        git branch -D pipeline || true
        git checkout -b $env.PIPELINE_BRANCH_NAME
        echo "test" >> test
        git add .
        git commit -m "commit from pipeline"
        git push --set-upstream origin $env.PIPELINE_BRANCH_NAME

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/bin/git
          ~/.usr/bin/curl


