name: PHP Composer

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: usr/bin/git

    - run: echo 111
    - run: echo 222

    - name: Pipeline test
      run: lsb_release -a

    - name: Install Git
      run: |
        sudo apt install git
        git --version

    - name: Delete branch
      run: git branch -D pipeline || true

    - name: Create branch
      run: git checkout -b pipeline

    - name: Stage changes
      run: git add .

    - name: Commit changes
      run: git commit -m "commit from pipeline"

    - name: Push changes
      run: git push


