name: PHP Composer

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: echo 111
    - run: echo 222

    - name: Git setup
      run: |
        lsb_release -a
        sudo apt install git
        git --version
        which git
        git config --global user.email "pipeline@github.com"
        git config --global user.name "pipeline"

    - name: Delete branch
      run: git branch -D pipeline || true

    - name: Create branch
      run: git checkout -b pipeline

    - name: Stage changes
      run: git add .

    - name: Commit changes
      run: git commit -m "commit from pipeline"

    - name: Push changes
      run: git push


